# Generated by Django 5.2.8 on 2025-11-12 12:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom unique du rôle (en minuscules, sans espaces, ex: editor, manager)",
                        max_length=50,
                        unique=True,
                        verbose_name="nom du rôle",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Nom affiché dans l'interface",
                        max_length=100,
                        verbose_name="nom d'affichage",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si coché, ce rôle sera attribué par défaut aux nouveaux utilisateurs",
                        verbose_name="rôle par défaut",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dictionnaire JSON des permissions spécifiques au rôle",
                        verbose_name="permissions",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle",
                "verbose_name_plural": "rôles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Format: Nom Prénom(s) ou Nom_Prénom(s) ou NomPrénom(s)",
                        max_length=255,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="Adresse e-mail",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Désigne si cet utilisateur doit être considéré comme actif. Désélectionnez ceci plutôt que de supprimer le compte.",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'inscription",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Mot de passe"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Formats acceptés: JPG, JPEG, PNG, GIF, WEBP. Taille max: 5MB",
                        null=True,
                        upload_to=django_authentication.models.user_profile_picture_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "gif", "webp"]
                            )
                        ],
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rôle de l'utilisateur dans le système",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="django_authentication.role",
                        verbose_name="rôle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_manage_users", "Peut gérer les utilisateurs"),
                    ("can_view_dashboard", "Peut voir le dashboard"),
                ],
            },
        ),
    ]
